#ifndef OPENDFN_ENUM_H
#define OPENDFN_ENUM_H

enum class rangeMethod {
    SQUAREIN,
    SQUAREOUT,
    SQUAREON,
    CIRCLEIN,
    CIRCLEON,
    CIRCLEOUT,
    PLANELEFT,
    PLANEON,
    PLANERIGHT,
    POLYGONIN,
    POLYGONON,
    POLYGONOUT,
    BYCOORD
};

enum class random_method {
    RANDOM_NULL,
    RANDOM_CONSTANT,
    RANDOM_GAUSSE,
    RANDOM_UNIFORM,
    RANDOM_EXPONENTINAL,
    RANDOM_LOG_NORMAL,
    RANDOM_POWER,
    RANDOM_FISHER
};

#endif
